-- MySQL Script generated by MySQL Workbench
-- Fri Sep 10 15:40:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nombre_operador` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `user_operador` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tipo_identificacion` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `idOPERADOR_UNIQUE` (`id_user` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plazas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plazas` (
  `idPlazas` INT NOT NULL,
  `Tipo_plaza` VARCHAR(45) NOT NULL,
  `CodigoPlaza` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPlazas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehiculos` (
  `idVehiculos` INT NOT NULL,
  `placa` VARCHAR(45) NOT NULL,
  `tipo_vehiculo` VARCHAR(10) NOT NULL,
  `id_Plazas_vehiculo` INT NOT NULL,
  `fecha_Salida` DATE NOT NULL,
  `fecha_entrada` DATE NOT NULL,
  PRIMARY KEY (`idVehiculos`),
  INDEX `vehiculo_plaza_idx` (`id_Plazas_vehiculo` ASC) VISIBLE,
  CONSTRAINT `vehiculo_plaza`
    FOREIGN KEY (`id_Plazas_vehiculo`)
    REFERENCES `mydb`.`Plazas` (`idPlazas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `id_Factura` INT NOT NULL AUTO_INCREMENT,
  `id_Vehiculos` INT NOT NULL,
  `costo_Total` DOUBLE NOT NULL,
  `fecha` DATE NOT NULL,
  `id_userFactura` INT NOT NULL,
  PRIMARY KEY (`id_Factura`),
  UNIQUE INDEX `idFactura_UNIQUE` (`id_Factura` ASC) VISIBLE,
  INDEX `factura_vehiculos_idx` (`id_Vehiculos` ASC) VISIBLE,
  INDEX `factura_operador_idx` (`id_userFactura` ASC) VISIBLE,
  CONSTRAINT `factura_vehiculos`
    FOREIGN KEY (`id_Vehiculos`)
    REFERENCES `mydb`.`Vehiculos` (`idVehiculos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `factura_operador`
    FOREIGN KEY (`id_userFactura`)
    REFERENCES `mydb`.`Usuarios` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tarifa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tarifa` (
  `idTarifa` INT NOT NULL AUTO_INCREMENT,
  `precio_x_minuto` DOUBLE NOT NULL,
  `precio_Fraccion` DOUBLE NOT NULL,
  `Fraccion` INT NOT NULL,
  PRIMARY KEY (`idTarifa`),
  UNIQUE INDEX `idTarifa_UNIQUE` (`idTarifa` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
